name: Daily News Scraper

on:
  schedule:
    - cron: '0 22 * * *' 
  workflow_dispatch: 

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # v3에서 v4로 업그레이드 (경고 해결)

      - name: Set up Python
        uses: actions/setup-python@v5 # v4에서 v5로 업그레이드 (경고 해결)
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests feedparser # 필수 라이브러리 설치

      - name: Run script
        env:
          NAVER_ID: ${{ secrets.NAVER_ID }}
          NAVER_SECRET: ${{ secrets.NAVER_SECRET }}
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PW: ${{ secrets.GMAIL_PW }} # 이 이름이 Secrets와 같아야 합니다!
        run: python main.py
