name: Daily News Scraper

on:
  schedule:
    - cron: '0 22 * * *' # 매일 오전 7시 실행
  workflow_dispatch:      # 수동 실행 버튼 활성화

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests feedparser

      - name: Run script
        env:
          NAVER_ID: ${{ secrets.NAVER_ID }}
          NAVER_SECRET: ${{ secrets.NAVER_SECRET }}
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PW: ${{ secrets.GMAIL_PW }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }} # Secrets에 등록한 이름과 같아야 함
        run: python news_bot.py
